// <auto-generated />
using System;
using FitnessCoach.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCoach.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCoach.Domain.Models.UsuarioPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<double>("EstaturaCm")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivoActual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ObjetivoActualTipo");

                    b.Property<double>("PesoKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UsuariosPerfil");
                });

            modelBuilder.Entity("FitnessCoach.Domain.Models.UsuarioPerfil", b =>
                {
                    b.OwnsMany("FitnessCoach.Domain.Models.RegistroProgreso", "HistorialProgreso", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("Fecha")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Notas")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("PesoKg")
                                .HasColumnType("float");

                            b1.Property<int>("UsuarioPerfilId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("UsuarioPerfilId");

                            b1.ToTable("RegistrosProgreso", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UsuarioPerfilId");
                        });

                    b.Navigation("HistorialProgreso");
                });
#pragma warning restore 612, 618
        }
    }
}
